Repository Quansight/Quansight-website, pull requests merged in 2022-06, with the labels that each got.

#173 Fix/duplicate link on llc library
  apps/consulting/components/Tiles/Tiles.tsx
  apps/consulting/components/Tiles/types.ts
  apps/consulting/components/Tiles/utils/areValidSectionTiles.ts
  apps/consulting/pages/library/index.tsx
  apps/consulting/utils/divideLibraryTiles/divideLibraryTiles.ts
Labels: type: bug 🐛, LLC 🤝, area: react, area: Vercel

#169 Feat/llc blog image caption
  apps/consulting/components/BlogArticle/BlogPost/BlogPost.tsx
  apps/consulting/tailwind.config.js
  apps/labs/tailwind.config.js
  libs/shared/types/src/utils/richText.ts
  libs/shared/types/tsconfig.lib.json
  libs/shared/utils/src/createMarkup/createMarkup.ts
  libs/shared/utils/src/createMarkup/richTextBlokResolver/components/ErrorNotification/ErrorNotificatoin.tsx
  libs/shared/utils/src/createMarkup/richTextBlokResolver/components/ErrorNotification/types.ts
  libs/shared/utils/src/createMarkup/richTextBlokResolver/getRichTextBlokPropsByType/getRichTextBlokPropsByType.ts
  libs/shared/utils/src/createMarkup/richTextBlokResolver/getRichTextBlokPropsByType/mappers/getRichTextFigureProps.ts
  libs/shared/utils/src/createMarkup/richTextBlokResolver/getRichTextBlokPropsByType/types.ts
  libs/shared/utils/src/createMarkup/richTextBlokResolver/richTextBlokResolver.tsx
  libs/shared/utils/src/createMarkup/richTextBlokResolver/richTextBloks/RichTextFigure/RichTextFigure.tsx
  libs/shared/utils/src/createMarkup/richTextBlokResolver/richTextBloks/RichTextFigure/types.ts
  libs/shared/utils/src/createMarkup/richTextBlokResolver/richTextBloks/richTextBloksMap.ts
  libs/shared/utils/src/createMarkup/richTextBlokResolver/richTextRawBlok/bloks/richTextFigure.ts
  libs/shared/utils/src/createMarkup/richTextBlokResolver/richTextRawBlok/richTextRawBlok.ts
  libs/shared/utils/src/createMarkup/richTextBlokResolver/types.ts
  libs/shared/utils/src/createMarkup/richTextBlokResolver/utils/isValidString.ts
Labels: type: enhancement 💅🏼, LLC 🤝, type: content 📝, area: Storyblok

#166 docs: Add missing steps to running locally
  README.md
Labels: area: documentation 📖, type: enhancement 💅🏼, needs: review 👀, owner: Naturaily

#234 docs: How to update dependencies
  README.md
Labels: area: documentation 📖, type: enhancement 💅🏼, needs: review 👀, owner: Naturaily

#232 fix: Hero image should cover the space not shrink to fit
  libs/shared/ui-components/src/Hero/Hero.tsx
Labels: labs 🔭, LLC 🤝, needs: review 👀, owner: Naturaily, type: design flaw 🧯

#231 fix: Give columns even width at md breakpoint
  apps/consulting/components/Columns/Column/Column.tsx
Labels: type: bug 🐛, needs: review 👀, area: react, owner: Naturaily
