Repository Quansight/Quansight-website, pull requests merged in 2022-08, with the labels that each got.

#411 Change /blog and /staffing redirects to permanent
  apps/consulting/next.config.js
Labels: LLC 🤝, owner: Quansight, type: maintenance 🛠, area: Vercel

#412 Add `/labs` redirect to labs.quansight.org
  apps/consulting/next.config.js
Labels: type: enhancement 💅🏼, LLC 🤝, owner: Quansight, area: Vercel

#413 Add labs.quansight.com -> .org redirect
  apps/consulting/next.config.js
Labels: type: enhancement 💅🏼, LLC 🤝, owner: Quansight, area: Vercel

#415 [BLOG] Add feature image for Scipy 2022 Labs blog
  apps/labs/posts/alt-text-scipy-2022.md
Labels: labs 🔭, type: content 📝, owner: Quansight

#417 chore: merge develop into main
  apps/labs/posts/alt-text-scipy-2022.md
Labels: area: assets 📸, labs 🔭, type: content 📝

#419 [BLOG] Add pytorch-tensoriterator-internals
  apps/labs/posts/pytorch-tensoriterator-internals.md
  apps/labs/public/posts/pytorch-tensoriterator-internals/blog_hero_var1.svg
  apps/labs/public/posts/pytorch-tensoriterator-internals/feature.png
Labels: labs 🔭, type: content 📝

#427 Add Storyblok content note for #426 fix
  apps/consulting/CHANGELOG.md
Labels: LLC 🤝, type: content 📝, owner: Quansight, status: merge ready ✨

#429 Update LLC CHANGELOG with PPL Post
  apps/consulting/CHANGELOG.md
Labels: LLC 🤝, type: content 📝, owner: Quansight, status: merge ready ✨

#357 docs: Cover new system design in readme
  README.md
Labels: area: documentation 📖, priority: high 🌋, needs: review 👀, area: CI/CD 👷🏻, area: Vercel

#432 [DOC] Minor fixes/adds to README
  README.md
Labels: area: documentation 📖, type: content 📝, owner: Quansight
