Repository Quansight/Quansight-website, pull requests merged in 2023-09, with the labels that each got.

#765 [BLOG] Array API support in scikit-learn
  apps/labs/posts/array-api-support-scikit-learn.md
  apps/labs/public/posts/array-api-support-scikit-learn/benchmark_results.png
  apps/labs/public/posts/array-api-support-scikit-learn/data-api-scikit-learn-logos-hero.png
  apps/labs/public/posts/array-api-support-scikit-learn/data-api-scikit-learn-logos.png
Labels: type: content 📝

#772 Fix authors field in Array API in scikit-learn blog post
  apps/labs/posts/array-api-support-scikit-learn.md
Labels: type: bug 🐛, labs 🔭

#771 Release 20230919
  apps/labs/posts/array-api-support-scikit-learn.md
  apps/labs/public/posts/array-api-support-scikit-learn/benchmark_results.png
  apps/labs/public/posts/array-api-support-scikit-learn/data-api-scikit-learn-logos-hero.png
  apps/labs/public/posts/array-api-support-scikit-learn/data-api-scikit-learn-logos.png
Labels: needs: review 👀, type: release 🏷
